name: DEC_env
channels:
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - notebook
  - numpy
  - seaborn
  - matplotlib=3.3.4
  - pip
  - pip:
    - obspy
    - tensorflow == 2.5.0
    - sklearn == 0.24.1
